# Generated by Django 5.2.3 on 2025-06-21 05:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم التصنيف')),
                ('slug', models.SlugField(help_text='يُستخدم في الـ URL، يُفضل أن يكون بالإنجليزية ويحتوي على حروف وأرقام وشرطات فقط.', max_length=120, unique=True, verbose_name='الاسم اللطيف (Slug)')),
            ],
            options={
                'verbose_name': 'تصنيف خبر',
                'verbose_name_plural': 'تصنيفات الأخبار',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الخبر')),
                ('slug', models.SlugField(help_text='يُستخدم في الـ URL، عادةً ما يتم إنشاؤه تلقائيًا من العنوان.', max_length=220, unique_for_date='publication_date', verbose_name='الاسم اللطيف (Slug)')),
                ('content', models.TextField(verbose_name='محتوى الخبر')),
                ('excerpt', models.TextField(blank=True, help_text='مقدمة قصيرة للخبر، إذا تُرك فارغًا سيتم استخدام جزء من المحتوى.', verbose_name='مقتطف (اختياري)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/%Y/%m/', verbose_name='صورة الخبر (اختياري)')),
                ('publication_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاريخ النشر')),
                ('is_important', models.BooleanField(db_index=True, default=False, help_text='الأخبار الهامة قد تظهر بشكل بارز أو في قسم خاص.', verbose_name='خبر مهم (مثبت)؟')),
                ('is_published', models.BooleanField(db_index=True, default=True, help_text='إلغاء التحديد لإخفاء الخبر مؤقتًا دون حذفه.', verbose_name='منشور؟')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_news', to=settings.AUTH_USER_MODEL, verbose_name='الناشر')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_items', to='news.newscategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'خبر/إعلان',
                'verbose_name_plural': 'الأخبار والإعلانات',
                'ordering': ['-publication_date'],
                'indexes': [models.Index(fields=['slug', 'publication_date'], name='news_newsit_slug_3485de_idx'), models.Index(fields=['-publication_date', 'is_published', 'is_important'], name='news_newsit_publica_344266_idx')],
            },
        ),
    ]
