# Generated by Django 5.2.3 on 2025-06-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='slug',
            field=models.SlugField(blank=True, help_text='يُستخدم في الـ URL، عادةً ما يتم إنشاؤه تلقائيًا من العنوان إذا تُرك فارغًا.', max_length=220, unique=True, verbose_name='الاسم اللطيف (Slug)'),
        ),
    ]
