# Generated by Django 5.2.3 on 2025-06-21 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsitem_slug'),
        ('news', '0003_alter_newsitem_slug_unique'),
    ]

    operations = [
    ]
