# Generated by Django 5.2.3 on 2025-06-21 19:58

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_merge_20250621_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscategory',
            name='slug',
            field=models.SlugField(help_text='يُستخدم في الـ URL...', max_length=120, unique=True, verbose_name='الاسم اللطيف (Slug)'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='excerpt',
            field=models.TextField(blank=True, help_text='مقدمة قصيرة...', verbose_name='مقتطف (اختياري)'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/%Y/%m/', validators=[news.models.validate_file_size], verbose_name='صورة الخبر (اختياري)'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='is_important',
            field=models.BooleanField(db_index=True, default=False, help_text='الأخبار الهامة...', verbose_name='خبر مهم (مثبت)؟'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='إلغاء التحديد...', verbose_name='منشور؟'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='slug',
            field=models.SlugField(blank=True, help_text='يُستخدم في الـ URL، عادةً ما يتم إنشاؤه تلقائيًا من العنوان إذا تُرك فارغًا.', max_length=220, unique=True, verbose_name='الاسم اللطيف (Slug) للـ URL'),
        ),
    ]
