# Generated by Django 5.2.3 on 2025-06-21 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الشارة')),
                ('description', models.TextField(verbose_name='وصف الشارة')),
                ('icon_class', models.CharField(blank=True, help_text='مثال: fas fa-star, mdi mdi-trophy. اترك فارغًا إذا استخدمت صورة.', max_length=100, null=True, verbose_name='فئة CSS للأيقونة (Font Awesome)')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='badges_icons/', verbose_name='صورة أيقونة الشارة (اختياري)')),
                ('criteria_description', models.TextField(blank=True, null=True, verbose_name='وصف معيار تحقيق الشارة')),
                ('badge_type_key', models.CharField(blank=True, db_index=True, help_text='مفتاح برمجي فريد لنوع الشارة (مثل TASK_COMPLETER_10).', max_length=50, null=True, unique=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='لتحديد ترتيب ظهور الشارات.')),
            ],
            options={
                'verbose_name': 'شارة',
                'verbose_name_plural': 'شارات',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاكتساب')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by_users', to='achievements.badge', verbose_name='الشارة المكتسبة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges_earned', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'شارة مستخدم مكتسبة',
                'verbose_name_plural': 'شارات المستخدمين المكتسبة',
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['user', 'badge'], name='achievement_user_id_5af5fa_idx'), models.Index(fields=['user', '-earned_at'], name='achievement_user_id_d7ca0a_idx')],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
