# Generated by Django 5.2.3 on 2025-07-12 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم التحدي')),
                ('description', models.TextField(verbose_name='وصف التحدي')),
                ('challenge_type', models.CharField(choices=[('tasks_completed', 'إكمال عدد من المهام'), ('files_read', 'قراءة عدد من الملفات'), ('pomodoro_sessions', 'إكمال جلسات بومودورو'), ('forum_posts', 'المساهمة بمنشورات في المنتدى'), ('group_messages', 'إرسال رسائل في المجموعات'), ('custom', 'تحدي مخصص')], max_length=50, verbose_name='نوع التحدي')),
                ('target_value', models.PositiveIntegerField(help_text='مثال: 10 مهام، 5 ملفات، 3 جلسات بومودورو', verbose_name='القيمة المستهدفة')),
                ('xp_reward', models.PositiveIntegerField(default=0, verbose_name='مكافأة نقاط الخبرة')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('badge_reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='achievements.badge', verbose_name='شارة المكافأة')),
            ],
            options={
                'verbose_name': 'تحدي دراسي',
                'verbose_name_plural': 'تحديات دراسية',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievementStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.PositiveIntegerField(default=0, verbose_name='إجمالي نقاط الخبرة')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='المستوى الحالي')),
                ('last_xp_update', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث لنقاط الخبرة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_stats', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إحصائيات إنجازات المستخدم',
                'verbose_name_plural': 'إحصائيات إنجازات المستخدمين',
                'ordering': ['-total_xp'],
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='مقدار نقاط الخبرة')),
                ('activity', models.CharField(max_length=255, verbose_name='النشاط')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'عملية نقاط الخبرة',
                'verbose_name_plural': 'عمليات نقاط الخبرة',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserStudyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_progress', models.PositiveIntegerField(default=0, verbose_name='التقدم الحالي')),
                ('completed', models.BooleanField(default=False, verbose_name='اكتمل')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='achievements.studychallenge', verbose_name='التحدي')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_challenges', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تحدي مستخدم دراسي',
                'verbose_name_plural': 'تحديات المستخدمين الدراسية',
                'ordering': ['-joined_at'],
                'unique_together': {('user', 'challenge')},
            },
        ),
    ]
