# Generated by Django 5.2.3 on 2025-06-21 05:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.TextField(verbose_name='نص الاقتباس/النصيحة')),
                ('author_or_source', models.CharField(blank=True, max_length=200, null=True, verbose_name='الكاتب/المصدر')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط (يمكن عرضه)')),
            ],
            options={
                'verbose_name': 'اقتباس/نصيحة يومية',
                'verbose_name_plural': 'اقتباسات/نصائح يومية',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('dark_mode_enabled', models.BooleanField(default=False, verbose_name='تفعيل الوضع الليلي')),
                ('pomodoro_work_duration', models.PositiveIntegerField(default=25, help_text='القيمة الافتراضية هي 25 دقيقة. (من 1 إلى 120)', verbose_name='مدة جلسة العمل (دقائق)')),
                ('pomodoro_short_break_duration', models.PositiveIntegerField(default=5, help_text='القيمة الافتراضية هي 5 دقائق. (من 1 إلى 60)', verbose_name='مدة الراحة القصيرة (دقائق)')),
                ('pomodoro_long_break_duration', models.PositiveIntegerField(default=15, help_text='القيمة الافتراضية هي 15 دقيقة. (من 1 إلى 90)', verbose_name='مدة الراحة الطويلة (دقائق)')),
                ('pomodoro_sessions_before_long_break', models.PositiveIntegerField(default=4, help_text='القيمة الافتراضية هي 4 جلسات. (من 1 إلى 10)', verbose_name='عدد جلسات العمل قبل الراحة الطويلة')),
            ],
            options={
                'verbose_name': 'الملف الشخصي للمستخدم',
                'verbose_name_plural': 'الملفات الشخصية للمستخدمين',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('verb', models.CharField(max_length=255, verbose_name='الفعل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف التفصيلي للإشعار')),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('unread', models.BooleanField(db_index=True, default=True, verbose_name='غير مقروء')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='التوقيت')),
                ('actor_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_notifications_%(app_label)s_%(class)s_related', to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_notifications_%(app_label)s_%(class)s_related', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'إشعارات',
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['recipient', 'unread'], name='core_notifi_recipie_3dcb0e_idx')],
            },
        ),
    ]
