# Generated by Django 5.2.3 on 2025-07-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المورد')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('link', models.URLField(verbose_name='الرابط')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط (للعرض العام)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مورد تعليمي',
                'verbose_name_plural': 'الموارد التعليمية',
                'ordering': ['-created_at'],
            },
        ),
    ]
