# Generated by Django 5.2.3 on 2025-07-05 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studentsummary',
            name='files_manag_subject_df51a7_idx',
        ),
        migrations.AddField(
            model_name='studentsummary',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='إذا تم تحديده، سيتم إخفاء اسم المستخدم.', verbose_name='رفع الملخص بشكل مجهول'),
        ),
        migrations.AddField(
            model_name='studentsummary',
            name='is_public',
            field=models.BooleanField(default=False, help_text='إذا تم تحديده، سيكون الملخص متاحًا للجميع بعد الموافقة.', verbose_name='مشاركة الملخص مع الجميع'),
        ),
        migrations.AddIndex(
            model_name='studentsummary',
            index=models.Index(fields=['subject', 'status', 'is_public'], name='files_manag_subject_d167a9_idx'),
        ),
    ]
