# Generated by Django 5.2.3 on 2025-07-05 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_manager', '0002_remove_studentsummary_files_manag_subject_df51a7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mainfile',
            name='academic_year',
            field=models.CharField(blank=True, help_text='مثال: 2023-2024', max_length=9, null=True, verbose_name='السنة الدراسية'),
        ),
        migrations.AddField(
            model_name='mainfile',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الأول'), ('second', 'الفصل الثاني')], help_text='اختر الفصل الدراسي.', max_length=6, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AddIndex(
            model_name='mainfile',
            index=models.Index(fields=['academic_year', 'semester', '-uploaded_at'], name='files_manag_academi_255c63_idx'),
        ),
    ]
