# Generated by Django 5.2.3 on 2025-07-05 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files_manager', '0003_mainfile_academic_year_mainfile_semester_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='السؤال')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='الإجابة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التفاعل')),
                ('main_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_interactions', to='files_manager.mainfile', verbose_name='المحاضرة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_interactions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تفاعل شات',
                'verbose_name_plural': 'تفاعلات الشات',
                'ordering': ['-created_at'],
            },
        ),
    ]
