# Generated by Django 5.2.3 on 2025-07-06 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notification_time_before', models.PositiveIntegerField(default=5, help_text='عدد الدقائق للتذكير قبل الصلاة', verbose_name='الوقت قبل الصلاة (بالدقائق)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_reminders', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تذكير صلاة',
                'verbose_name_plural': 'تذكيرات الصلاة',
            },
        ),
        migrations.CreateModel(
            name='PrayerTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer_type', models.CharField(choices=[('fajr', 'الفجر'), ('sunrise', 'الشروق'), ('dhuhr', 'الظهر'), ('asr', 'العصر'), ('maghrib', 'المغرب'), ('isha', 'العشاء')], max_length=10, verbose_name='نوع الصلاة')),
                ('time', models.TimeField(verbose_name='وقت الصلاة')),
                ('date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
                ('is_notified', models.BooleanField(default=False, verbose_name='تم التذكير')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_times', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'وقت صلاة',
                'verbose_name_plural': 'أوقات الصلاة',
                'ordering': ['time'],
                'unique_together': {('user', 'prayer_type', 'date')},
            },
        ),
    ]
