# Generated by Django 5.2.3 on 2025-07-06 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer_times', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='اسم المدينة')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='خط الطول')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='البلد')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='الولاية/المقاطعة')),
                ('timezone', models.CharField(blank=True, max_length=100, null=True, verbose_name='المنطقة الزمنية (IANA)')),
            ],
            options={
                'verbose_name': 'موقع الصلاة',
                'verbose_name_plural': 'مواقع الصلاة',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='prayerreminder',
            options={'verbose_name': 'إعداد تذكير الصلاة', 'verbose_name_plural': 'إعدادات تذكير الصلاة'},
        ),
        migrations.AlterModelOptions(
            name='prayertime',
            options={'ordering': ['date', 'time'], 'verbose_name': 'وقت صلاة', 'verbose_name_plural': 'أوقات الصلاة'},
        ),
        migrations.AlterUniqueTogether(
            name='prayertime',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='prayerreminder',
            name='is_active',
        ),
        migrations.AddField(
            model_name='prayerreminder',
            name='enabled',
            field=models.BooleanField(default=True, help_text='تفعيل هذا الخيار سيسمح بتشغيل صوت الأذان عند وقت الصلاة.', verbose_name='تفعيل التذكيرات الصوتية'),
        ),
        migrations.AlterField(
            model_name='prayerreminder',
            name='notification_time_before',
            field=models.PositiveIntegerField(default=5, help_text='عدد الدقائق قبل وقت الصلاة لإرسال التذكير.', verbose_name='التذكير قبل الصلاة (بالدقائق)'),
        ),
        migrations.AlterField(
            model_name='prayerreminder',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_reminder_settings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='prayertime',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='prayertime',
            name='prayer_type',
            field=models.CharField(choices=[('fajr', 'الفجر'), ('sunrise', 'الشروق'), ('dhuhr', 'الظهر'), ('asr', 'العصر'), ('maghrib', 'المغرب'), ('isha', 'العشاء'), ('imsak', 'الإمساك'), ('midnight', 'منتصف الليل')], max_length=10, verbose_name='نوع الصلاة'),
        ),
        migrations.AlterField(
            model_name='prayertime',
            name='time',
            field=models.TimeField(verbose_name='الوقت'),
        ),
        migrations.AlterField(
            model_name='prayertime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_times_set', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterUniqueTogether(
            name='prayertime',
            unique_together={('user', 'date', 'prayer_type')},
        ),
        migrations.AddIndex(
            model_name='prayertime',
            index=models.Index(fields=['user', 'date'], name='prayer_time_user_id_9025c7_idx'),
        ),
    ]
