# Generated by Django 5.2.3 on 2025-07-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer_times', '0002_location_alter_prayerreminder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerreminder',
            name='daily_werd_reminder_enabled',
            field=models.BooleanField(default=False, help_text='تفعيل هذا الخيار لتذكيرك بقراءة الورد اليومي.', verbose_name='تفعيل تذكير الورد اليومي'),
        ),
        migrations.AddField(
            model_name='prayerreminder',
            name='daily_werd_reminder_time',
            field=models.TimeField(default='07:00:00', help_text='الوقت الذي ترغب فيه بتلقي تذكير الورد اليومي (مثال: 07:00 صباحاً).', verbose_name='وقت تذكير الورد اليومي'),
        ),
        migrations.AlterField(
            model_name='prayerreminder',
            name='enabled',
            field=models.BooleanField(default=True, help_text='تفعيل هذا الخيار سيسمح بتشغيل صوت الأذان عند وقت الصلاة.', verbose_name='تفعيل تذكيرات الصلاة'),
        ),
    ]
