# Generated by Django 5.2.3 on 2025-07-06 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer_times', '0003_prayerreminder_daily_werd_reminder_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerreminder',
            name='is_notified_evening_adhkar_today',
            field=models.BooleanField(default=False, verbose_name='تم إشعار أذكار المساء اليوم'),
        ),
        migrations.AddField(
            model_name='prayerreminder',
            name='is_notified_morning_adhkar_today',
            field=models.BooleanField(default=False, verbose_name='تم إشعار أذكار الصباح اليوم'),
        ),
        migrations.AddField(
            model_name='prayerreminder',
            name='is_notified_werd_today',
            field=models.BooleanField(default=False, verbose_name='تم إشعار الورد اليومي اليوم'),
        ),
        migrations.AddField(
            model_name='prayerreminder',
            name='last_notification_reset_date',
            field=models.DateField(default=datetime.date.today, verbose_name='آخر تاريخ لإعادة تعيين الإشعارات'),
        ),
    ]
