# Generated by Django 5.2.3 on 2025-06-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPrayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان الدعاء (اختياري)')),
                ('text', models.TextField(verbose_name='نص الدعاء')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='لتحديد ترتيب ظهور الدعاء (الأقل أولاً).')),
                ('is_active', models.BooleanField(default=True, help_text='إلغاء التحديد لإخفاء الدعاء مؤقتًا.', verbose_name='نشط (معروض)؟')),
            ],
            options={
                'verbose_name': 'دعاء امتحان',
                'verbose_name_plural': 'أدعية الامتحانات',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان النصيحة/الترتيب')),
                ('description', models.TextField(verbose_name='شرح النصيحة/الترتيب')),
                ('category', models.CharField(choices=[('general', 'نصائح عامة/ترتيبات'), ('before', 'قبل الامتحان (مذاكرة)'), ('during', 'أثناء الامتحان'), ('after', 'بعد الامتحان')], db_index=True, default='general', max_length=20, verbose_name='تصنيف النصيحة')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='لتحديد ترتيب ظهور النصيحة داخل تصنيفها (الأقل أولاً).')),
                ('is_active', models.BooleanField(default=True, help_text='إلغاء التحديد لإخفاء النصيحة مؤقتًا.', verbose_name='نشطة (معروضة)؟')),
            ],
            options={
                'verbose_name': 'نصيحة/ترتيب امتحان',
                'verbose_name_plural': 'نصائح وترتيبات الامتحانات',
                'ordering': ['category', 'order', 'id'],
            },
        ),
    ]
