# Generated by Django 5.2.3 on 2025-07-12 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('exam_prep', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='معرف الكائن المبلغ عنه')),
                ('reason', models.TextField(verbose_name='سبب الإبلاغ')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإبلاغ')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('reviewed', 'تمت المراجعة'), ('resolved', 'تم الحل'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات المشرف')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع المحتوى المبلغ عنه')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_reports', to=settings.AUTH_USER_MODEL, verbose_name='المُبلغ')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='تمت المراجعة بواسطة')),
            ],
            options={
                'verbose_name': 'إبلاغ',
                'verbose_name_plural': 'إبلاغات',
                'ordering': ['status', '-reported_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='exam_prep_r_content_565ca2_idx'), models.Index(fields=['status', '-reported_at'], name='exam_prep_r_status_0c8501_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(help_text="مثال: 'login', 'file_view', 'task_completed', 'group_message'", max_length=100, verbose_name='نوع النشاط')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ والوقت')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الكائن المرتبط')),
                ('details', models.JSONField(blank=True, default=dict, help_text='بيانات JSON إضافية حول النشاط (مثل مدة المشاهدة، حجم الملف، نتيجة الاختبار).', null=True, verbose_name='تفاصيل إضافية')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='نوع الكائن المرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'نشاط المستخدم',
                'verbose_name_plural': 'أنشطة المستخدمين',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'activity_type'], name='exam_prep_u_user_id_d1d90f_idx'), models.Index(fields=['activity_type', 'timestamp'], name='exam_prep_u_activit_a5a14c_idx')],
            },
        ),
    ]
